### ISSUE TITLE
Memory leak using playbin to loop video

### ISSUE THREAD

**Issue by msmithatcarmanahsigns** [Freescale/gstreamer-imx#137]
Hi, I seem to have found a memory leak while using playbin to loop a video.  I posted in the i.MX community forums but this may be a better place for it, so I've copied the text here as well.

I'm using kernel 3.14.28 and gstreamer1.0-plugins-imx_0.12.1 to play video, and I'm looping it using the about-to-finish signal of playbin.  When my application receives the signal, it sets the URI for playbin to the same file and the video loops seamlessly.

However, there seems to be a memory leak.  The application slowly uses more and more memory until the oom killer closes it.  Valgrind says memory is definitely lost but doesn't trace back further than g_malloc.

I enabled CMA kernel debug messages, and I see many messages like this:

cma: dma_alloc_from_contiguous(): memory range at XXXX is busy, retrying

Watching the message bus for GST_MESSAGE_EOS and seeking to the beginning of the file at that point does not seem to leak memory.  For now I will have the application do that instead, but I thought it would be appropriate to file a bug report here.

Here's a link to the i.MX community post: https://community.nxp.com/message/875368  I've posted a sample application there that demonstrates the problem.

Thanks for all your hard work on this framework!

**Comment by dv1** [comment]
First, I was not aware that using the about-to-finish signal for looping works. That signal is called from within the streaming thread. How do you do it? Do you use gst_element_seek() against playbin itself?

Because perhaps this hints at the reason. It sounds like one GstBuffer with DMA memory inside is not properly unref'd. Try running your application with the GST_TRACE=mem-live environment variable (when you do looping with about-to-finish). I unfortunately cannot run the test program yet, because I am finishing other urgent things.

**Comment by msmithatcarmanahsigns** [comment]
Yes, I am currently watching for GST_MESSAGE_EOS and then calling gst_element_seek() against playbin to loop.  That works ok.

The way I was doing it that caused the memory leak was by connecting playbin's about-to-finish signal to a function that set the uri of playbin to the same file, thus looping it.  Like this:

...
g_signal_connect(playbin, "about-to-finish", G_CALLBACK(prepare_next_stream), (gpointer)"file:///home/user/test.264");
...

void prepare_next_stream(GstElement *obj, gpointer uri)
{
	g_print ("Got about-to-finish\n");
	g_object_set (obj, "uri", (const char*) uri, NULL);
}

The full code is attached to the i.MX6 community post.
