### ISSUE TITLE
Running out of memory when resolution changes

### ISSUE THREAD

**Issue by DuBistKomisch** [Freescale/gstreamer-imx#153]
We've traced an issue where our live stream freezes back to this.

Relevant debug level 4 log: [output.txt](https://github.com/Freescale/gstreamer-imx/files/983322/output.txt)

The sending client can switch resolution during the stream, which puts the appropriate packet into the h264 bitstream, which causes the caps to change to the new resolution.

This apparently re-initialises the decoder, so it re-allocates the frame buffers. Unfortunately it allocates the new one before deallocating the old one, so in the case when switching from 1440x1080 to 1920x1080 it runs out while almost done allocating. It works fine switching from 810x1080 to 1440x1080 (earlier in logs) and 810x1080 to 1920x1080 (not in logs) though.

I managed to get around this by upping CMA from 256 to 384M in the kernel parameters in u-boot after reading https://github.com/Freescale/gstreamer-imx/issues/130. I tried 512M first but this causes a kernel panic. Maybe it varies with your specific hardware.

Would it be possible to make the decoder free the old frame buffers before allocating the new ones? I'm guessing it's probably like that for a reason though, so please close this if so. Mostly just posting this in case anyone runs into the same problem.

edit: lol this issue got my account automatically flagged?

**Comment by DuBistKomisch** [comment]
@angolini ?

This is still an open question, can at least say it's not possible to fix before closing. I can only just barely raise the memory enough to handle switching between two almost 1920x1080 streams without getting a kernel panic, it's probably still possible to run out of memory in some cases.

**Comment by otavio** [comment]
@dv1

**Comment by angolini** [comment]
Hi, it's me again. What is the status of this issue, please?

**Comment by DuBistKomisch** [comment]
This is basically a feature request, so if it's not going to be considered, feel free to close it!

**Comment by angolini** [comment]
oh! I see, thanks

**Comment by dv1** [comment]
@DuBistKomisch You should retry this with the new gstreamer-imx version (2.0), which is a rewrite that also supports imx8 machines. Also, unfortunately, in general, this behavior is difficult to avoid, since the old buffer pool may still be in use when a new buffer pool is allocated. This can happen when the last few frames from the old stream are still buffered somewhere downstream in the pipeline while new data comes in that requires a different resolution. Those frames have a dependency on their associated buffer pools, meaning that these pools are kept alive by the frames, and are deallocated only when those frames are gone.

**Comment by angolini** [comment]
@DuBistKomisch, I think it is more clear now. Could you, please let us know your thoughts and close this issue?
