### ISSUE TITLE
multi-instance imxeglvivsink issues

### ISSUE THREAD

**Issue by FrankBau** [Freescale/gstreamer-imx#167]
Hi,

I use framebuffer as graphical backend on a i.MX6Q board, and imxeglvivsink works pretty well with it, thanks!
Now, I was trying to use dual/quad pipelines like:
```
gst-launch-1.0 -v imxv4l2videosrc device=/dev/video1 imx-capture-mode=4 ! tee name=t \
t. ! queue ! imxeglvivsink window-x-coord=0 window-y-coord=0 window-width=640 window-height=360 force-aspect-ratio=0 \
t. ! queue ! imxeglvivsink window-x-coord=640 window-y-coord=0 window-width=640 window-height=360 force-aspect-ratio=0 \
t. ! queue ! imxeglvivsink window-x-coord=0 window-y-coord=360 window-width=640 window-height=360 force-aspect-ratio=0 \
t. ! queue ! imxeglvivsink window-x-coord=640 window-y-coord=360 window-width=640 window-height=360 force-aspect-ratio=0
```
which works too, but shows tearing. From the FAQ I have learned that FB_MULTI_BUFFER=2 can remove tearing, but this seems to work only for a single instance of eglvivsink: Each instance creates its own gst_imx_egl_viv_sink_gles2_renderer_thread which are all calling eglSwapBuffers.

I may try to spent some efforts into a multi-instance version of imxeglvivsink, but I don't see an easy way.
Yes, one could use a video compositor component upfront, but  finally I want to do some camera undistortion and want to use GLSL shaders for each individual camera input.

**Comment by dv1** [comment]
This cannot be done with imxeglvivsink since multiple instances will try to flip pages at the same time. Latest GStreamer versions have gotten some additional Vivante GL support for uploads, so the Gst GL stack can be used for transformations. Patches have also been added to gstreamer-imx to interoperate with Gst GL (specifically, the GstPhysMemory structure from newer gst-plugins-bad versions is supported).

**Comment by FrankBau** [comment]
Thanks a lot for your quick response. I will look into the GL stack. Frank.
