### ISSUE TITLE
building for android

### ISSUE THREAD

**Issue by ystreet** [Freescale/gstreamer-imx#21]
Here are the steps I needed to perform in order to build the gstreamer-imx plugins on android.  I jot them down here for future reference.  If I had more time to learn the waf build script I would propose patches.
1. disable building v4l2src
2. comment out the pthread check (android includes it in libc however it still needs the -pthread flag)
3. Build static plugins by changing all occurences of 'cshlib' to 'cstlib' and #define GST_PLUGIN_BUILD_STATIC in all the plugin files before #include <gst/gst.h>

**Comment by dv1** [comment]
Recently I started to improve Android support. As part of that, I wrote support for generating .la files. It is unfinished, however it does work. Here is the patch file (not committed yet because it is a proof-of-concept): https://www.dropbox.com/s/9735tlnxm1ag52o/gstimx-add-la-file-generation-for-android-builds-with-cerbero.patch

**Comment by angolini** [comment]
So far, Android support is a TODO item. I'm going to close this issue. (please feel free to reopen in case of any update)

**Comment by samuelmusser** [comment]
Has there been any more follow up on Android support? I understand in the README it is still on the to do list. I would like to cross compile the newer plugins for Android Gstreamer on i.MX8MQ.
