### ISSUE TITLE
imxipuvideotransform & videotestsrc issue

### ISSUE THREAD

**Issue by BorisDuch** [Freescale/gstreamer-imx#212]
Hi,

I am facing an issue when trying to convert a video-test signal from  Bayer BGGR  to I420 using the IPU: the output is a dark frame. Oddly when I work with my color camera using imxv4l2videosrc it works fine.

My configuration is:
GStreamer 1.4.4
libgstimxipu 0.12.2
 
The code (bash script) is as follows:

JPEG_QUALITY=70
MAX_FILES=10

CAPS1=video/x-bayer,format=bggr,width=1280,height=1024
CAPS2=video/x-raw,format=I420,width=1280,height=1024

ENCODE="imxvpuenc_mjpeg quality-factor=$JPEG_QUALITY "
SINK="mmultifilesink location=/tmp/%T.jpg max-files=$MAX_FILES"

GST_PIPE="$SRC ! $CAPS1 ! imxipuvideotransform ! $CAPS2 ! $ENCODE ! $SINK"

gst-launch-1.0 $GST_PIPE

Thanks in advance for your help!

Boris

**Comment by dv1** [comment]
The IPU is known to be very picky and fragile. I usually try to avoid having to use it because of this. Unfortunately, a full fix would also require a driver rewrite, which is not feasible at the moment. I am busy currently updating libimxvpuapi to support the iMX8. After that, I'll start a substantial update to gstreamer-imx.
