### ISSUE TITLE
imxv4l2videosrc can't receive h.264 data

### ISSUE THREAD

**Issue by erlenner** [Freescale/gstreamer-imx#237]
My camera encodes h.264 data and exposes it through a v4l2 interface. I get linking errors when replacing v4l2src with imxv4l2videosrc in my pipeline. I guess it's because imxv4l2videosrc only expects raw video, while I need it to accept h.264.

Would it be possible to get support for more v4l2 data formats, like h.264, in the future? Maybe in v2? Do you have some sort of timeline on v2?

I appreciate all your hard work on this project.

**Comment by dv1** [comment]
Sorry for the inactivity due to lack of time. In v2, I recently added a rewritten imxv4l2videosrc element that is intended solely for use with the imx6 and the MIPI based video capture modules that use its mxc_v4l2 driver, and that one does not support h264. imx8 can use the default v4l2src instead.
