### ISSUE TITLE
Adding imxvpudec in google coral

### ISSUE THREAD

**Issue by Oppila-Microsystems** [Freescale/gstreamer-imx#310]
Hi,

I'm In the process of adding v4l2h264dec or imxvpudec

v4l2h264dec was not able to add. so i tried imxvpudec using the repo https://github.com/Freescale/gstreamer-imx

 but the dependencies  [libimxdmabuffer](https://github.com/Freescale/libimxdmabuffer)  not installing which is saying

--imx-linux-headers-path is not set

if i set the path then its giving

Could not find linux/mxcfb.h in path

how to resolve this ?

is this procedure for running os or cross compilation?

and what are these path ?

    CC
    CFLAGS
    LDFLAGS
    PKG_CONFIG_PATH
    PKG_CONFIG_SYSROOT_DIR

please give me the detailed information

thank you

**Comment by dougnazar** [comment]
You don't mention which kernel you're using. You'll need a kernel with the i.MX additions. For instance I'm in the middle of updating to [5.15-2.0.x-imx](https://github.com/Freescale/linux-fslc/tree/5.15-2.0.x-imx). `mxcfb.h` is under `include/uapi/linux` and will be installed if you use `make install_headers` or a build system that packages that.

**Comment by dv1** [comment]
As @dougnazar explained, you need an imx-kernel. That said, recently, I am now moving away from checking for `mxcfb.h`, since some sysroots don't package this anymore. libimxdmabuffer's latest version (1.1.3) no longer checks for it; libimxvpuapi will follow soon. But you still need to specify the path to the imx headers, since libimxdmabuffer needs to use the IPU and PxP headers for the corresponding allocators to work.
