### ISSUE TITLE
i.MX8MQ: 4k H.264 playback

### ISSUE THREAD

**Issue by cmeissl** [Freescale/gstreamer-imx#311]
Hi,

I am trying to get a 4k video run smoothly on an i.MX8MQ. 
When using the official gstreamer plugins + weston-imx I can make it run smoothly by enabling the tiling in the waylandsink.
Without tiling the video is choppy and a lot of buffers are dropped.

When using `imxvpudec_h264` I was unable to find out how to enable the tiling and the video is always choppy.
It looks like the tiling can be enabled in `libimxvpuapi` [here](https://github.com/Freescale/libimxvpuapi/blob/master/imxvpuapi2/imxvpuapi2_imx8m_hantro_decoder.c#L1234) by providing `IMX_VPU_API_DEC_OPEN_PARAMS_FLAG_USE_TILED_OUTPUT`, but I have not found a reference to that flag in `gstreamer-imx`.

Is 4k video playback currently possible with `gstreamer-imx`?

**Comment by dv1** [comment]
Sorry for the late reply. Tiling is not currently possible, but could be added. The main obstacle is what to put in the GStreamer caps. The elements in the NXP plugins add extra GstMeta fields to the buffers for this, but I am not sure this is a good approach. How to add Hantro tiling support to GStreamer is still being discussed.

However, I was able to play 4K video smoothly without tiling. This is doable with weston-imx, since the DCSS can work with un-tiled frames. It is the GPU that would have problems without tiling. Did you try combining `imxvpudec_h264` and weston-imx?

**Comment by dv1** [comment]
Commit ebbc5d3b13e497a4ef74be7e3f7c8408ac527b33 introduced support for 4x4 Hantro tiled frames. This format exists as NV12_4L4 in GStreamer. Closing this issue now, since it seems solved. If not, reopen please.
