### ISSUE TITLE
imxg2dvideotransform & framerate=1/1

### ISSUE THREAD

**Issue by d-lareg** [Freescale/gstreamer-imx#318]
SOC: i.MX 8M+
gstreamer-imx version: master

Hi,
I would like to exec a pipeline that only provides one image per second, no matter what the source stream is. I have a local RSTP stream running with 25FPS. The following pipeline works fine:

`gst-launch-1.0 -ve rtspsrc location="rtsp://192.168.1.2:8554/Streaming/Channels/101" latency=1000 ! queue ! rtph264depay ! h264parse ! imxvpudec_h264 ! imxg2dvideotransform ! video/x-raw,width=768,height=512 ! videorate ! "video/x-raw,framerate=1/1" ! fakesink`

Since imxg2dvideotransform also has a framerate property I would like to execute the frame dropping using the VPU with:

`gst-launch-1.0 -ve rtspsrc location="rtsp://192.168.1.2:8554/Streaming/Channels/101" latency=1000 ! queue ! rtph264depay ! h264parse ! imxvpudec_h264 ! imxg2dvideotransform ! video/x-raw,width=768,height=512,framerate=1/1 ! fakesink`

But the mentioned pipeline crashes and only runs if I set framerate=25/1 which is doing nothing.

Is this a bug or is this behavior intended?

**Comment by d-lareg** [comment]
Hi, and thanks for your quick response.
My choice of words was a little bit misleading. The pipe does not crashes but throws an error. The log for GST_DEBUG=3 is attached.
[gst_log.txt](https://github.com/Freescale/gstreamer-imx/files/11949302/gst_log.txt)

**Comment by dv1** [comment]
Yes, this makes sense. The framerate won't be changed by the existing elements - it will still be 25 FPS. But you apply a capsfilter that limits the allowed caps to 1 FPS. Hence the not-negotiated error. A videorate element is what you want here.

Can you elaborate on "and only runs if I set framerate=25/1 which is doing nothing" though? What do you mean, "doing nothing"? As in: It is redundant, since 25 FPS is already the input framerate? Or as in: nothing arrives at the fakesink?

**Comment by d-lareg** [comment]
If I set framerate=25/1 everything works fine since it matches the stream framerate. I wasn't clear about that it is only filter. You can close the issue since everything works as expected. 👍

**Comment by dv1** [comment]
Alright!
