### ISSUE TITLE
Is it possible add tv source (TV encoder such as adv7180) plugin

### ISSUE THREAD

**Issue by jordonwu** [Freescale/gstreamer-imx#64]
Is it possible add tv source (TV encoder such as adv7180) plugin? such as this patch(https://github.com/Gateworks/meta-gateworks/blob/danny/recipes-multimedia/gst-plugins/gst-fsl-plugin-3.0.1/enable_tvin_source.patch) for gst-fsl-plugin-3.0.1

**Comment by dv1** [comment]
It certainly is. Main problem is that I don't have this hardware. Also, from my understanding, the adv7180 is an analog TV receiver. I don't think there are analog TV signals left in my region.

**Comment by Gateworks** [comment]
The adv7180 is handled fine by gstreamer-imx without any additional patches. The patch referenced was for the old Freescale plugins where they had a different plugin for interlaced vs non-interlaced video.

We use the adv7180 on many of the Gateworks boards with gstreamer-imx.

**Comment by jordonwu** [comment]
@Gateworks , Yes, gstreamer-imx is worked well with adv7180. This command "gst-launch-1.0 imxv4l2videosrc device=/dev/video0 ! imxeglvivsink" is worked on my board. 
But when I using qt5.6(qml's VideoOutput) is not work with gstreamer-imx. Any suggestion and tips? Thanks

**Comment by dv1** [comment]
Any updates on this? Any logs available? Since I cannot test this, it is very difficult to do anything without logs.

**Comment by Gateworks** [comment]
@jordonwu - I can't test this either - I don't know what software you are running on the board. Can you point me to a filesystem image you are using?

**Comment by dv1** [comment]
I now got some hardware that has an adv7180, and it works well for me. However, the framerate is fixed to whatever the input requires (25 fps with PAL, 30 with NTSC signals). Perhaps qt 5.6 doesn't handle that properly; I have observed that some pipelines do "stutter" for some reason. After the upcoming release, I'll try to clean up the v4l2 source, perhaps this solves these problems. Closing this for now, since the adv7180 does work with gstreamer-imx.
