### ISSUE TITLE
Gstreamer not building in Yocto image

### ISSUE THREAD

**Issue by lewicki-pk** [Freescale/gstreamer-imx#65]
Hello, I'm unable to compile gstreamer-imx recipe.
I'm using phytec yocto distribution (PD15.2.0) based on freescale arm.
Here's my what I get when trying to bake the recipe:
https://gist.github.com/lewicki-pk/20ec89fe2b65e37d702a

My recipe is like that:
https://gist.github.com/ad007197e6d0e139025b.git

In my opinion the kernel version may be the issue here (I'm building with 3.19.5), but I'm not sure.
Please help

BR,
Piotr

**Comment by dv1** [comment]
I am unfamiliar with this distribution. The include error you see here did happen in the past, and was fixed by prepending (!) `usr/src/kernel/include/uapi` to the include paths. For unclear reasons, this apparently didn't happen here. What kernel version is this? Check out the wscript in the root directory. You'll see a `check_linux_headers` function as well as the test that checks if the kernel version is 3.5.0 or higher. Only in that case it adds the uapi path.

**Comment by lewicki-pk** [comment]
I guess the issue was with the newer kernel than in fsc's linux-imx (3.19 vs 3.14). I'm closing this issue. Sorry for problem.
