### ISSUE TITLE
imxipuvideotransform for resolutions over 2048x2048

### ISSUE THREAD

**Issue by carlos-aguero** [Freescale/gstreamer-imx#82]
This is actually a comment more than an issue. Currently the imxipuvideotransform can't transform images over 1968x1128 the IPU has a limit of 1024x1024 but the ipu driver can pass the image four times for doing 2048x2048. Would it be possible to do colorspace transformation for 2592x1944 by dividing the image and passing it to the IPU lets say 6 times? I would say it is possible and involve changes at kernel side and at imxipuvideotransform side. Any comment?

Regards, and thank you for your time

**Comment by dv1** [comment]
Thanks for your comment. I have been trying something like this in the past. The idea would be to do the tiling completely manually. That is, break up frames into tiles with max. 1024x1024 pixels. But the problem is that this is only one IPU limitation - downscaling by a factor of more than 8 also seems to not be possible. See https://github.com/Freescale/gstreamer-imx/issues/27#issuecomment-149328711 . It is possible to do a multi-stage scaling, though it is not exactly trivial. I do see though that the IPU elements need a rework like this badly. I will pick it up again.
